### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by schillingbtk** [BasiliusCarver/TicTacTOBOL#2]
Hello

First: Thank you! Very nice

Could you tell us something about the Distribution / Terminal you use? A Standard Terminal like bash, sh or xterm did not handle DISPLAY AT line-column

**Comment by ShaunLawrie** [comment]
It should work in most terminals after compiling with open-cobol.
Did `cobc -W -x -o TicTacTOBOL TicTacTOBOL.cbl` work to compile the application?
The shell (bash/sh etc...) shouldn't impact execution but the terminal emulator might. I was able to run this on xterm in Ubuntu.
![image](https://user-images.githubusercontent.com/13159458/104859721-fe7f1680-598b-11eb-82c1-6dfeb571942a.png)
![image](https://user-images.githubusercontent.com/13159458/104859724-0b036f00-598c-11eb-91ee-7df54b014aec.png)
